spring:
  redis:
    lettuce:
      pool:
        max-idle: 60
        min-idle: 5
        max-active: 300
        max-wait: 3000ms
    database: 5
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 100ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.196.219.8:3306/final?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: chundengtai123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: tm_hikaricp_pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  offsetAsPageNum: true

debug: false
happyMall:
  sms:
    accessKeyId: 1
    accessKeySecret: 1
    regTemplate: 1
    sign: 1

